### ISSUE TITLE
Bug: Error message does not appear

### ISSUE THREAD

**Issue by ogzcode** [mateenagy/vue-formify#4]
Hello, 
I took the exact example on the [doc page](https://vue-formify.matenagy.me/docs/components/error/), but the error message does not appear. We need to give the ref we created for the form to `FormifyForm`. This is missing in the doc page.

[Stackblitz](https://stackblitz.com/edit/vitejs-vite-mwosf6?file=index.html,src%2Fstyle.css,src%2FApp.vue&terminal=dev)

Also, in the code below, the p tag is not closed.

```
<template>
    <Error error-for="email" v-slot="{error}">
        <p class="error-message">Error: {{ error }}</
    </Error>
</template>
```

@mateenagy

**Comment by mateenagy** [comment]
Hi @ogzcode 

You are right! I fixed the template issue and update the documentation to use template ref.

Thank you for noticing these issues!
