### ISSUE TITLE
Where is the repository for the docs?

### ISSUE THREAD

**Issue by PizzaConsole** [mateenagy/vue-formify#9]
Noticed a few typos in the docs, wondering where the repo was for that, if I could fork and help contribute.

**Comment by mateenagy** [comment]
It's not public yet, but I think I will merge it to this repo. I would be more than happy for your contribution. English is not my first language and sometimes I just update it fast for new features or bugfix and leave some mistake.

I will notify you if it merged.

**Comment by mateenagy** [comment]
@PizzaConsole Docs source code is now merged in this repository under `docs` folder.
